### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "anand babu",
  "email": "gpmc@gmail.com",
  "password": "babu@123",
  "role": "officer"
}

### 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "gpmc@gmail.com",
  "password": "babu@123"
}


### Profile   (finding the profile cata)
GET http://localhost:5000/api/test/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMxODI1LCJleHAiOjE3NzE2MTgyMjV9.wmupihzJ0WaNFC7Ke_C17Cfouu5hkpRrL1tvf32A1eo


###
### Save Student Profile
POST http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMyODEzLCJleHAiOjE3NzE2MTkyMTN9.n0Arx2_K5CZkoD6wrBKtuvDMD6XuLemyZ45Q4Yk04IA
Content-Type: application/json

{
  "rollNo": "23EG112E34",
  "branch": "IT",
  "cgpa": 8.0,
  "backlogs": 0,
  "skills": ["React","Node","MongoDB","Java"],
  "batchYear": 2027
}

### Get Student Profile
GET http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMyODEzLCJleHAiOjE3NzE2MTkyMTN9.n0Arx2_K5CZkoD6wrBKtuvDMD6XuLemyZ45Q4Yk04IA

###
POST http://localhost:5000/api/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc3MmQ5N2Y2MWM1NWNiMjJiNGZiOCIsInJvbGUiOiJvZmZpY2VyIiwiaWF0IjoxNzcxNTMzMDM3LCJleHAiOjE3NzE2MTk0Mzd9.zofb9wxXWh8LtwTedsHeKo7DmlHa61hkCWNJYU9GVuI
Content-Type: application/json

{
  "name": "gpmc",
  "email": "gpmc@gmail.com",
  "hrName": "Suresh",
  "location": "Hyderbad"
}



### student job
POST http://localhost:5000/api/job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMxODI1LCJleHAiOjE3NzE2MTgyMjV9.wmupihzJ0WaNFC7Ke_C17Cfouu5hkpRrL1tvf32A1eo
Content-Type: application/json

{
  "companyId": "6997732b7f61c55cb22b4fbc",
  "title": "Software Engineer",
  "minCGPA": 7,
  "maxBacklogs": 0,
  "requiredSkills": ["React","Node"],
  "salary": "6 LPA",
  "deadline": "2026-06-01"
}


### job apply
POST http://localhost:5000/api/application/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMyODEzLCJleHAiOjE3NzE2MTkyMTN9.n0Arx2_K5CZkoD6wrBKtuvDMD6XuLemyZ45Q4Yk04IA
Content-Type: application/json

{
  "jobId": "699773817f61c55cb22b4fbf"
}




