### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "thrishool",
  "email": "epam@gmail.com",
  "password": "thrishool",
  "role": "officer"
}

### 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "epam@gmail.com",
  "password": "thrishool"
}


### Profile   (finding the profile cata)
GET http://localhost:5000/api/test/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc3MmQ5N2Y2MWM1NWNiMjJiNGZiOCIsInJvbGUiOiJvZmZpY2VyIiwiaWF0IjoxNzcxNjk0MjgyLCJleHAiOjE3NzE3ODA2ODJ9.JhelfDq1QzQ2rMKFspBycnLij1VY4xW2oK8nMVQJasI


###
### Save Student Profile
POST http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTllOWNjNzAxYzQ3Yjk3NDJkYjkwNyIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNjk0NTYxLCJleHAiOjE3NzE3ODA5NjF9.DzcFoba57LV6lwDQTmO6DQc5vwqlSzMaozeZ37g-KJ4
Content-Type: application/json

{
  "rollNo": "23EG112E01",
  "branch": "DS",
  "cgpa": 8.8,
  "backlogs": 0,
  "skills": ["React","Node","MongoDB","Java","Cpp"],
  "batchYear": 2027
}

### Get Student Profile
GET http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTllOWNjNzAxYzQ3Yjk3NDJkYjkwNyIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNjk0NTYxLCJleHAiOjE3NzE3ODA5NjF9.DzcFoba57LV6lwDQTmO6DQc5vwqlSzMaozeZ37g-KJ4

###
POST http://localhost:5000/api/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTllYjIxNzAxYzQ3Yjk3NDJkYjkxMiIsInJvbGUiOiJvZmZpY2VyIiwiaWF0IjoxNzcxNjk0OTA3LCJleHAiOjE3NzE3ODEzMDd9.ceaIRspVurWu9NoLUCBKLvJm4UOHJWs9hQ5xPVVZQ6U
Content-Type: application/json

{
  "name": "epam-software",
  "email": "epam@gmail.com",
  "hrName": "thota",
  "location": "Hyderbad"
}



### student job (company token-officer)
POST http://localhost:5000/api/job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTc2ZTFiN2Y2MWM1NWNiMjJiNGZhOCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNTMxODI1LCJleHAiOjE3NzE2MTgyMjV9.wmupihzJ0WaNFC7Ke_C17Cfouu5hkpRrL1tvf32A1eo
Content-Type: application/json

{
  "companyId": "6999eb64701c47b9742db916c",
  "title": "Software Engineer",
  "minCGPA": 7,
  "maxBacklogs": 0,
  "requiredSkills": ["React","Node"],
  "salary": "6 LPA",
  "deadline": "2026-06-01"
}


### job apply(token-student)
POST http://localhost:5000/api/application/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTllOWNjNzAxYzQ3Yjk3NDJkYjkwNyIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcxNjk0NTYxLCJleHAiOjE3NzE3ODA5NjF9.DzcFoba57LV6lwDQTmO6DQc5vwqlSzMaozeZ37g-KJ4
Content-Type: application/json

{
  "jobId": "699773817f61c55cb22b4fbf"
}




