### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "suresh",
  "email": "hr@infosys.com",
  "password": "infosys@123",
  "role": "officer"
}
### 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "hr@infosys.com",
  "password": "infosys@123"
}


### Profile   (finding the profile cata)
GET http://localhost:5000/api/test/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODYxZjBiYTMxY2FiZTVhNzRjNWQ3MyIsInJvbGUiOiJmYWN1bHR5IiwiaWF0IjoxNzcwMzk3NDgzLCJleHAiOjE3NzA0ODM4ODN9.f177wNP6kvmQ7MoGzSx3c2DU1oVVsaUIpnTEW2YF_gg



###
### Save Student Profile
POST http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODYyNDBlMGY1MmY3ODNhNDg0ZWRlNCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcwMzk4Nzc0LCJleHAiOjE3NzA0ODUxNzR9.S-fws9Hcu-eZB9gtvKJ5gMDTwYS7KztPuScsIp9mp_I
Content-Type: application/json

{
  "rollNo": "23EG112E63",
  "branch": "CSE",
  "cgpa": 8.2,
  "backlogs": 0,
  "skills": ["React","Node","MongoDB"],
  "batchYear": 2026
}

### Get Student Profile
GET http://localhost:5000/api/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODYyNDBlMGY1MmY3ODNhNDg0ZWRlNCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzcwMzk4Nzc0LCJleHAiOjE3NzA0ODUxNzR9.S-fws9Hcu-eZB9gtvKJ5gMDTwYS7KztPuScsIp9mp_I

###
POST http://localhost:5000/api/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTVmOTNhMTI3MjdkOWU1NzE4MTdhZSIsInJvbGUiOiJvZmZpY2VyIiwiaWF0IjoxNzcxNDM2MzcxLCJleHAiOjE3NzE1MjI3NzF9.lfinsEVxJrg9P0pH7kZVTVrxLwhY2MamNm_u-4TjWAY
Content-Type: application/json

{
  "name": "Infosys",
  "email": "hr@infosys.com",
  "hrName": "Suresh",
  "location": "Bangalore"
}



### student job
POST http://localhost:5000/api/job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTVmOTNhMTI3MjdkOWU1NzE4MTdhZSIsInJvbGUiOiJvZmZpY2VyIiwiaWF0IjoxNzcxNDM2MzcxLCJleHAiOjE3NzE1MjI3NzF9.lfinsEVxJrg9P0pH7kZVTVrxLwhY2MamNm_u-4TjWAY
Content-Type: application/json

{
  "companyId": "6995f96612727d9e571817b1",
  "title": "Software Engineer",
  "minCGPA": 7,
  "maxBacklogs": 0,
  "requiredSkills": ["React","Node"],
  "salary": "6 LPA",
  "deadline": "2026-06-01"
}
